# Generated by Django 5.0.7 on 2026-08-07 19:05

import apps.attachments.storage
import apps.attachments.validators
import apps.projects.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('industrial', 'Industrial'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('government', 'Government'), ('mixed_use', 'Mixed use'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('image', models.ImageField(blank=True, null=True, storage=apps.attachments.storage.get_protected_storage, upload_to=apps.projects.models.project_image_upload_path, validators=[apps.projects.models.validate_project_image])),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('operational', 'Operational')], default='planning', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='facilities.facility')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role_type', models.CharField(choices=[('primary_manager', 'Primary manager'), ('engineer', 'Engineer'), ('supervisor', 'Supervisor'), ('viewer', 'Viewer')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(storage=apps.attachments.storage.get_protected_storage, upload_to=apps.projects.models.project_document_upload_path, validators=[apps.attachments.validators.validate_attachment_file])),
                ('original_file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.projects.models.ImmutableHistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sequence_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('initial_progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('current_progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('needs_modification', 'Needs Modification')], default='not_started', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhaseReviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('disposition', models.CharField(blank=True, choices=[('needs_modification', 'Needs modification'), ('final_rejection', 'Final rejection')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_logs', to='projects.projectphase')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.projects.models.ImmutableHistoryMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PhaseProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('work_completed', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_logs', to='projects.projectphase')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=(apps.projects.models.ImmutableHistoryMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['facility'], name='project_facility_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'expected_completion_date'], name='project_status_expected_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('expected_completion_date__gte', models.F('start_date'))), name='project_expected_after_start'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('actual_completion_date__isnull', True), ('actual_completion_date__gte', models.F('start_date')), _connector='OR'), name='project_actual_after_start'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), _connector='OR'), name='project_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), _connector='OR'), name='project_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('planning', 'in_progress', 'completed', 'operational'))), name='project_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('facility_type__in', ('commercial', 'residential', 'industrial', 'healthcare', 'education', 'government', 'mixed_use', 'other'))), name='project_facility_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status__in', ('completed', 'operational')), _negated=True), ('actual_completion_date__isnull', False), _connector='OR'), name='project_completed_has_actual'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'operational'), _negated=True), ('facility__isnull', False), _connector='OR'), name='project_operational_has_facility'),
        ),
        migrations.AddIndex(
            model_name='projectassignment',
            index=models.Index(fields=['user', 'project'], name='project_assign_user_proj_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'role_type'), name='unique_project_user_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.CheckConstraint(check=models.Q(('role_type__in', ('primary_manager', 'engineer', 'supervisor', 'viewer'))), name='project_assignment_role_valid'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'created_at'], name='project_document_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.CheckConstraint(check=models.Q(('file_size__gt', 0)), name='project_document_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectdocument',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='project_document_uploader_req'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['project', 'sequence_number'], name='phase_project_sequence_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['project', 'status'], name='phase_project_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.UniqueConstraint(fields=('project', 'sequence_number'), name='unique_project_phase_sequence'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('sequence_number__gt', 0)), name='phase_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('initial_progress__gte', 0), ('initial_progress__lte', 100)), name='phase_initial_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('current_progress__gte', 0), ('current_progress__lte', 100)), name='phase_current_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('current_progress__gte', models.F('initial_progress'))), name='phase_current_gte_initial'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ('low', 'medium', 'high'))), name='phase_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('not_started', 'in_progress', 'completed', 'rejected', 'needs_modification'))), name='phase_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('expected_completion_date__gte', models.F('start_date'))), name='phase_expected_after_start'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(('actual_completion_date__isnull', True), models.Q(('actual_start_date__isnull', False), ('actual_completion_date__gte', models.F('actual_start_date'))), _connector='OR'), name='phase_actual_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('approved_by__isnull', True), ('approved_at__isnull', True)), models.Q(('approved_by__isnull', False), ('approved_at__isnull', False)), _connector='OR'), name='phase_approval_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'completed'), _negated=True), ('current_progress', Decimal('100.00')), _connector='OR'), name='phase_completed_progress_full'),
        ),
        migrations.AddConstraint(
            model_name='phasereviewlog',
            constraint=models.CheckConstraint(check=models.Q(('decision__in', ('approved', 'rejected'))), name='phase_review_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='phasereviewlog',
            constraint=models.CheckConstraint(check=models.Q(('disposition__isnull', True), ('disposition__in', ('needs_modification', 'final_rejection')), _connector='OR'), name='phase_review_disposition_valid'),
        ),
        migrations.AddConstraint(
            model_name='phasereviewlog',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'approved'), ('disposition__isnull', True)), models.Q(('decision', 'rejected'), ('disposition__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='phase_review_payload_valid'),
        ),
        migrations.AddConstraint(
            model_name='phasereviewlog',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='phase_review_reviewer_required'),
        ),
        migrations.AddIndex(
            model_name='phaseprogresslog',
            index=models.Index(fields=['phase', 'created_at'], name='phase_progress_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='phaseprogresslog',
            constraint=models.CheckConstraint(check=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='phase_progress_log_range'),
        ),
        migrations.AddConstraint(
            model_name='phaseprogresslog',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='phase_progress_author_required'),
        ),
    ]
