# Generated by Django 5.0.7 on 2026-08-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='created_from_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_facility', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['status'], name='facility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['type'], name='facility_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ('commercial', 'residential', 'industrial', 'healthcare', 'education', 'government', 'mixed_use', 'other'))), name='facility_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('operational', 'under_maintenance', 'decommissioned'))), name='facility_status_valid'),
        ),
    ]
