# Generated by Django 5.0.7 on 2026-08-07 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role_type', models.CharField(choices=[('operations_manager', 'Operations manager'), ('security_officer', 'Security officer'), ('viewer', 'Viewer')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='facilities.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'facility'], name='facility_assign_user_fac_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='facilityassignment',
            constraint=models.UniqueConstraint(fields=('facility', 'user', 'role_type'), name='unique_facility_user_role_assignment'),
        ),
        migrations.AddConstraint(
            model_name='facilityassignment',
            constraint=models.CheckConstraint(check=models.Q(('role_type__in', ('operations_manager', 'security_officer', 'viewer'))), name='facility_assignment_role_valid'),
        ),
    ]
