# Generated by Django 5.0.7 on 2026-08-07 19:05

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('kg', 'Kilogram'), ('g', 'Gram'), ('tonne', 'Tonne'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m', 'Metre'), ('m2', 'Square metre'), ('m3', 'Cubic metre'), ('box', 'Box'), ('pack', 'Pack'), ('roll', 'Roll'), ('sheet', 'Sheet'), ('bag', 'Bag')], max_length=10)),
                ('quantity_required', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_stock_threshold', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('usage_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_records', to='materials.material')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_consumption_records', to='projects.projectphase')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='submitted', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='materials.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['project', 'name'], name='material_project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['project', 'quantity_remaining'], name='material_project_remaining_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('min_stock_threshold__gte', 0), ('quantity_remaining__gte', 0), ('quantity_required__gte', 0), ('quantity_used__gte', 0)), name='material_quantities_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('quantity_used__lte', models.F('quantity_required'))), name='material_used_within_required'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('quantity_remaining', django.db.models.expressions.CombinedExpression(models.F('quantity_required'), '-', models.F('quantity_used')))), name='material_balance_consistent'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(check=models.Q(('unit__in', ('each', 'kg', 'g', 'tonne', 'l', 'ml', 'm', 'm2', 'm3', 'box', 'pack', 'roll', 'sheet', 'bag'))), name='material_unit_valid'),
        ),
        migrations.AddIndex(
            model_name='materialconsumptionrecord',
            index=models.Index(fields=['material', 'usage_date'], name='mat_consumption_usage_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialconsumptionrecord',
            constraint=models.CheckConstraint(check=models.Q(('quantity_used__gt', 0)), name='material_consumption_positive'),
        ),
        migrations.AddConstraint(
            model_name='materialconsumptionrecord',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='material_consumption_author_req'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['project', 'status'], name='mat_req_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['material', 'status'], name='mat_req_material_status_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['created_by', 'status'], name='mat_req_creator_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(check=models.Q(('quantity_requested__gt', 0)), name='material_request_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ('low', 'medium', 'high', 'urgent'))), name='material_request_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('submitted', 'reviewed', 'approved', 'rejected', 'completed'))), name='material_request_status_valid'),
        ),
    ]
