# Generated by Django 5.0.7 on 2026-08-07 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialrequest',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='material_request_creator_req'),
        ),
    ]
