# Generated by Django 5.0.7 on 2026-08-07 19:05

import apps.attachments.storage
import apps.security.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_type', models.CharField(choices=[('fire', 'Fire'), ('smoke', 'Smoke'), ('intrusion', 'Intrusion'), ('motion', 'Motion'), ('vehicle', 'Vehicle')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('source', models.CharField(choices=[('ai_detection', 'AI detection'), ('manual', 'Manual'), ('sensor', 'Sensor')], max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('snapshot_image', models.ImageField(blank=True, null=True, storage=apps.attachments.storage.get_protected_storage, upload_to=apps.security.models.security_snapshot_upload_path, validators=[apps.security.models.validate_security_snapshot])),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('converted', 'Converted'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_alerts', to='facilities.facility')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_security_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_number', models.CharField(default=apps.security.models.generate_incident_number, editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigation', 'Investigation'), ('transferred', 'Transferred'), ('closed', 'Closed')], default='open', max_length=20)),
                ('final_report', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_incidents', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_security_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='facilities.facility')),
                ('alert', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident', to='security.securityalert')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_taken', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='security.incident')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_incident_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['incident', 'taken_at'], name='incident_action_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='incidentaction',
            constraint=models.CheckConstraint(check=models.Q(('action_taken', ''), _negated=True), name='incident_action_required'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['facility', 'status'], name='security_alert_fac_status_idx'),
        ),
        migrations.AddIndex(
            model_name='securityalert',
            index=models.Index(fields=['-created_at'], name='security_alert_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('alert_type__in', ('fire', 'smoke', 'intrusion', 'motion', 'vehicle'))), name='security_alert_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('severity_level__in', ('low', 'medium', 'high', 'critical'))), name='security_alert_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('source__in', ('ai_detection', 'manual', 'sensor'))), name='security_alert_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('new', 'reviewed', 'converted', 'dismissed'))), name='security_alert_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='security_alert_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('source', 'ai_detection'), ('confidence_score__isnull', True), _connector='OR'), name='security_alert_confidence_ai_only'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['facility', 'status'], name='incident_facility_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('severity_level__in', ('low', 'medium', 'high', 'critical'))), name='incident_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('open', 'investigation', 'transferred', 'closed'))), name='incident_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='incident_creator_required'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'closed'), ('closed_by__isnull', False), ('closed_at__isnull', False)), models.Q(models.Q(('status', 'closed'), _negated=True), ('closed_by__isnull', True), ('closed_at__isnull', True)), _connector='OR'), name='incident_closure_fields_valid'),
        ),
    ]
