# Generated by Django 5.0.7 on 2026-08-07 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facilityassignment_and_more'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='securityalert',
            name='security_alert_type_valid',
        ),
        migrations.AlterField(
            model_name='securityalert',
            name='alert_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('smoke', 'Smoke'), ('intrusion', 'Intrusion'), ('motion', 'Motion'), ('unauthorized_person', 'Unauthorized Person'), ('emergency', 'Emergency'), ('vehicle', 'Vehicle')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='securityalert',
            constraint=models.CheckConstraint(check=models.Q(('alert_type__in', ('fire', 'smoke', 'intrusion', 'motion', 'unauthorized_person', 'emergency', 'vehicle'))), name='security_alert_type_valid'),
        ),
    ]
