# Generated by Django 5.0.7 on 2026-08-07 19:05

import apps.attachments.models
import apps.attachments.storage
import apps.attachments.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entity_type', models.CharField(choices=[('project_phase', 'Project phase'), ('phase_progress_log', 'Phase progress log'), ('daily_report', 'Daily report'), ('material_request', 'Material request'), ('material_consumption_record', 'Material consumption record')], max_length=64)),
                ('entity_id', models.UUIDField()),
                ('file', models.FileField(storage=apps.attachments.storage.get_protected_storage, upload_to=apps.attachments.models.attachment_upload_path, validators=[apps.attachments.validators.validate_attachment_file])),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('webp', 'WebP'), ('docx', 'DOCX'), ('xlsx', 'XLSX'), ('csv', 'CSV'), ('txt', 'Plain text')], max_length=10)),
                ('mime_type', models.CharField(max_length=127)),
                ('file_size', models.PositiveBigIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='attach_entity_target_idx')],
            },
        ),
    ]
