# Generated by Django 5.0.7 on 2026-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='entity_type',
            field=models.CharField(choices=[('project_phase', 'Project phase'), ('phase_progress_log', 'Phase progress log'), ('daily_report', 'Daily report'), ('material_request', 'Material request'), ('material_consumption_record', 'Material consumption record'), ('incident', 'Incident'), ('incident_action', 'Incident action')], max_length=64),
        ),
    ]
