# Generated by Django 5.0.7 on 2026-08-07 19:05

import apps.construction.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_date', models.DateField()),
                ('weather_condition', models.CharField(max_length=100)),
                ('workers_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('equipment_used', models.JSONField(default=list, validators=[apps.construction.models.validate_equipment_used])),
                ('report_content', models.TextField()),
                ('issues', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
