# Generated by Django 5.0.7 on 2026-08-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='projects.projectphase'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['project', 'report_date'], name='daily_report_project_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_date', 'created_by'), name='unique_daily_report_author_day'),
        ),
        migrations.AddConstraint(
            model_name='dailyreport',
            constraint=models.CheckConstraint(check=models.Q(('workers_count__gte', 0)), name='daily_report_workers_nonnegative'),
        ),
    ]
