# Generated by Django 5.0.7 on 2026-08-24 23:07

import apps.construction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_quality_sitephoto_dailyreport_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='equipment_used',
            field=models.JSONField(blank=True, default=list, validators=[apps.construction.models.validate_equipment_used]),
        ),
    ]
