# Generated by Django 5.0.7 on 2026-09-15 11:34

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_phase_critical_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('usgs', 'USGS'), ('gdacs', 'GDACS')], max_length=20)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('hazard_type', models.CharField(choices=[('earthquake', 'Earthquake'), ('tropical_cyclone', 'Tropical cyclone'), ('flood', 'Flood'), ('volcano', 'Volcano'), ('wildfire', 'Wildfire'), ('extreme_heat', 'Extreme heat'), ('extreme_cold', 'Extreme cold'), ('heavy_snow', 'Heavy snow'), ('high_wind', 'High wind'), ('heavy_rain', 'Heavy rain')], max_length=30)),
                ('provider_severity', models.CharField(blank=True, default='', max_length=32)),
                ('alert_level', models.CharField(blank=True, choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], max_length=10, null=True)),
                ('magnitude', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-2')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('depth_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-15')), django.core.validators.MaxValueValidator(Decimal('1000'))])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('2000'))])),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('occurred_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('provider_updated_at', models.DateTimeField()),
                ('provider_status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='active', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('last_seen_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectSafetyAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hazard_type', models.CharField(choices=[('earthquake', 'Earthquake'), ('tropical_cyclone', 'Tropical cyclone'), ('flood', 'Flood'), ('volcano', 'Volcano'), ('wildfire', 'Wildfire'), ('extreme_heat', 'Extreme heat'), ('extreme_cold', 'Extreme cold'), ('heavy_snow', 'Heavy snow'), ('high_wind', 'High wind'), ('heavy_rain', 'Heavy rain')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('actioned', 'Actioned'), ('closed', 'Closed'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('project_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('project_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('rule_code', models.CharField(max_length=100)),
                ('policy_version', models.PositiveIntegerField(default=0)),
                ('recommended_action', models.CharField(choices=[('suspend_outdoor_work', 'Suspend outdoor work'), ('delay_shift', 'Delay shift'), ('modify_working_hours', 'Modify working hours'), ('increase_precautions', 'Increase precautions'), ('inspect_site', 'Inspect site'), ('monitor', 'Monitor'), ('other', 'Other')], max_length=30)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('suspend_outdoor_work', 'Suspend outdoor work'), ('delay_shift', 'Delay shift'), ('modify_working_hours', 'Modify working hours'), ('increase_precautions', 'Increase precautions'), ('inspect_site', 'Inspect site'), ('monitor', 'Monitor'), ('other', 'Other')], max_length=30, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hazard_withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_safety_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_safety_alerts', to=settings.AUTH_USER_MODEL)),
                ('hazard_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_alerts', to='safety.hazardevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_alerts', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_safety_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='hazardevent',
            index=models.Index(fields=['hazard_type', '-occurred_at'], name='hazard_type_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='hazardevent',
            index=models.Index(fields=['provider', '-provider_updated_at'], name='hazard_provider_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='hazardevent',
            index=models.Index(fields=['provider_status', 'occurred_at'], name='hazard_status_occurred_idx'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_hazard_provider_event'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('provider__in', ('usgs', 'gdacs'))), name='hazard_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('hazard_type__in', ('earthquake', 'tropical_cyclone', 'flood', 'volcano', 'wildfire', 'extreme_heat', 'extreme_cold', 'heavy_snow', 'high_wind', 'heavy_rain'))), name='hazard_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('alert_level__isnull', True), ('alert_level__in', ('green', 'orange', 'red')), _connector='OR'), name='hazard_alert_level_valid'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('provider_status__in', ('active', 'withdrawn', 'expired'))), name='hazard_provider_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('provider_event_id', ''), _negated=True), name='hazard_provider_event_id_required'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('title', ''), _negated=True), name='hazard_title_required'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', Decimal('-90')), ('latitude__lte', Decimal('90'))), name='hazard_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', Decimal('-180')), ('longitude__lte', Decimal('180'))), name='hazard_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('magnitude__isnull', True), models.Q(('magnitude__gte', Decimal('-2')), ('magnitude__lte', Decimal('10'))), _connector='OR'), name='hazard_magnitude_range'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('radius_km__isnull', True), models.Q(('radius_km__gt', Decimal('0')), ('radius_km__lte', Decimal('2000'))), _connector='OR'), name='hazard_radius_range'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('revision__gte', 1)), name='hazard_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='hazard_validity_window_valid'),
        ),
        migrations.AddIndex(
            model_name='projectsafetyalert',
            index=models.Index(fields=['project', 'status', '-created_at'], name='safety_alert_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsafetyalert',
            index=models.Index(fields=['status', 'severity'], name='safety_alert_status_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsafetyalert',
            index=models.Index(fields=['-created_at'], name='safety_alert_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.UniqueConstraint(fields=('project', 'hazard_event'), name='unique_safety_alert_project_hazard'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('hazard_type__in', ('earthquake', 'tropical_cyclone', 'flood', 'volcano', 'wildfire', 'extreme_heat', 'extreme_cold', 'heavy_snow', 'high_wind', 'heavy_rain'))), name='safety_alert_hazard_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ('low', 'medium', 'high', 'critical'))), name='safety_alert_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('new', 'acknowledged', 'actioned', 'closed', 'dismissed'))), name='safety_alert_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('recommended_action__in', ('suspend_outdoor_work', 'delay_shift', 'modify_working_hours', 'increase_precautions', 'inspect_site', 'monitor'))), name='safety_alert_recommendation_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('decision__isnull', True), ('decision__in', ('suspend_outdoor_work', 'delay_shift', 'modify_working_hours', 'increase_precautions', 'inspect_site', 'monitor', 'other')), _connector='OR'), name='safety_alert_decision_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('distance_km__gte', Decimal('0'))), name='safety_alert_distance_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('project_latitude__gte', Decimal('-90')), ('project_latitude__lte', Decimal('90')), ('project_longitude__gte', Decimal('-180')), ('project_longitude__lte', Decimal('180'))), name='safety_alert_project_coords_range'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('acknowledged_at__isnull', True), ('acknowledged_by__isnull', True)), models.Q(('acknowledged_at__isnull', False), ('acknowledged_by__isnull', False)), _connector='OR'), name='safety_alert_ack_fields_paired'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('decision__isnull', True)), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('decision__isnull', False)), _connector='OR'), name='safety_alert_decision_fields_paired'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('resolved_at__isnull', True), ('resolved_by__isnull', True)), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False)), _connector='OR'), name='safety_alert_resolution_paired'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('decision', 'other'), _negated=True), models.Q(('decision_notes', ''), _negated=True), _connector='OR'), name='safety_alert_other_needs_notes'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('acknowledged_at__isnull', True), ('decision__isnull', True), ('resolved_at__isnull', True), ('status', 'new')), models.Q(('acknowledged_at__isnull', False), ('decision__isnull', True), ('resolved_at__isnull', True), ('status', 'acknowledged')), models.Q(('acknowledged_at__isnull', False), ('decision__isnull', False), ('resolved_at__isnull', True), ('status', 'actioned')), models.Q(('decision__isnull', False), ('resolved_at__isnull', False), ('status', 'closed')), models.Q(('decision__isnull', True), ('resolved_at__isnull', False), ('status', 'dismissed'), models.Q(('resolution_notes', ''), _negated=True)), _connector='OR'), name='safety_alert_status_fields_valid'),
        ),
    ]
