# Generated by Django 5.0.7 on 2026-09-16 07:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_safety_category'),
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTelegramRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_id', models.CharField(help_text='Numeric Telegram chat id. Never a phone number or an @username.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a numeric Telegram chat id (5-20 digits, optionally negative).', regex='^-?[0-9]{5,20}$')])),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_telegram_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyTelegramDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=64)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_deliveries', to='safety.projectsafetyalert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safety_telegram_deliveries', to='notifications.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='safety.safetytelegramrecipient')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='safetytelegramrecipient',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_safety_telegram_recipient_user'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramrecipient',
            constraint=models.CheckConstraint(check=models.Q(('chat_id__regex', '^-?[0-9]{5,20}$')), name='safety_telegram_chat_id_format'),
        ),
        migrations.AddIndex(
            model_name='safetytelegramdelivery',
            index=models.Index(fields=['status', 'updated_at'], name='safety_tg_delivery_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'recipient', 'event_key'), name='unique_safety_telegram_delivery_event'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramdelivery',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('queued', 'processing', 'sent', 'failed', 'skipped'))), name='safety_tg_delivery_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramdelivery',
            constraint=models.CheckConstraint(check=models.Q(('event_key', ''), _negated=True), name='safety_tg_delivery_event_key_present'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramdelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('sent_at__isnull', False), ('status', 'sent')), models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_at__isnull', True)), _connector='OR'), name='safety_tg_delivery_sent_at_paired'),
        ),
    ]
