# Generated by Django 5.0.7 on 2026-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_telegram_recipient_and_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardevent',
            name='area_polygons',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
