# Generated by Django 5.0.7 on 2026-09-16 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_phase_critical_priority'),
        ('safety', '0003_hazard_event_area_polygons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hazardevent',
            name='hazard_provider_valid',
        ),
        migrations.RemoveConstraint(
            model_name='hazardevent',
            name='hazard_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='projectsafetyalert',
            name='safety_alert_hazard_type_valid',
        ),
        migrations.AlterField(
            model_name='hazardevent',
            name='hazard_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('tropical_cyclone', 'Tropical cyclone'), ('flood', 'Flood'), ('volcano', 'Volcano'), ('wildfire', 'Wildfire'), ('extreme_heat', 'Extreme heat'), ('extreme_cold', 'Extreme cold'), ('heavy_snow', 'Heavy snow'), ('high_wind', 'High wind'), ('heavy_rain', 'Heavy rain'), ('dust_storm', 'Dust or sand storm')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hazardevent',
            name='provider',
            field=models.CharField(choices=[('usgs', 'USGS'), ('gdacs', 'GDACS'), ('mhews', 'MHEWS (Syria)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsafetyalert',
            name='hazard_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('tropical_cyclone', 'Tropical cyclone'), ('flood', 'Flood'), ('volcano', 'Volcano'), ('wildfire', 'Wildfire'), ('extreme_heat', 'Extreme heat'), ('extreme_cold', 'Extreme cold'), ('heavy_snow', 'Heavy snow'), ('high_wind', 'High wind'), ('heavy_rain', 'Heavy rain'), ('dust_storm', 'Dust or sand storm')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('provider__in', ('usgs', 'gdacs', 'mhews'))), name='hazard_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='hazardevent',
            constraint=models.CheckConstraint(check=models.Q(('hazard_type__in', ('earthquake', 'tropical_cyclone', 'flood', 'volcano', 'wildfire', 'extreme_heat', 'extreme_cold', 'heavy_snow', 'high_wind', 'heavy_rain', 'dust_storm'))), name='hazard_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='projectsafetyalert',
            constraint=models.CheckConstraint(check=models.Q(('hazard_type__in', ('earthquake', 'tropical_cyclone', 'flood', 'volcano', 'wildfire', 'extreme_heat', 'extreme_cold', 'heavy_snow', 'high_wind', 'heavy_rain', 'dust_storm'))), name='safety_alert_hazard_type_valid'),
        ),
    ]
