# Generated by Django 5.0.7 on 2026-09-16 21:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_mhews_provider_and_dust_storm_hazard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEventAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('usgs', 'USGS'), ('gdacs', 'GDACS'), ('mhews', 'MHEWS (Syria)')], max_length=20)),
                ('alias_identifier', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hazard_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_aliases', to='safety.hazardevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'alias_identifier'], name='hazard_alias_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hazardeventalias',
            constraint=models.UniqueConstraint(fields=('provider', 'alias_identifier'), name='unique_hazard_alias_identifier'),
        ),
        migrations.AddConstraint(
            model_name='hazardeventalias',
            constraint=models.CheckConstraint(check=models.Q(('provider__in', ('usgs', 'gdacs', 'mhews'))), name='hazard_alias_provider_valid'),
        ),
        migrations.AddConstraint(
            model_name='hazardeventalias',
            constraint=models.CheckConstraint(check=models.Q(('alias_identifier', ''), _negated=True), name='hazard_alias_identifier_required'),
        ),
    ]
