# Generated by Django 5.0.7 on 2026-09-18 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('safety', '0005_hazard_event_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safetytelegramrecipient',
            name='receives_worker_instructions',
            field=models.BooleanField(default=False, help_text='Receives approved worker-protection instructions for projects this user is actively assigned to. Off by default: enrolling someone is an explicit decision, never a side effect of having a destination.'),
        ),
        migrations.CreateModel(
            name='SafetyActionProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('decision_type', models.CharField(choices=[('worker_protection', 'Worker protection'), ('asset_protection', 'Asset protection')], max_length=20)),
                ('proposed_action', models.CharField(choices=[('suspend_outdoor_work', 'Suspend outdoor work'), ('delay_shift', 'Delay shift'), ('modify_working_hours', 'Modify working hours'), ('increase_precautions', 'Increase precautions'), ('inspect_site', 'Inspect site'), ('monitor', 'Monitor'), ('other', 'Other')], max_length=30)),
                ('proposal_notes', models.TextField(help_text="The proposing manager's justification. Always required.")),
                ('status', models.CharField(choices=[('pending_manager_review', 'Pending manager review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_manager_review', max_length=25)),
                ('proposed_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('affected_assets', models.ManyToManyField(blank=True, help_text='Asset-protection scope. Never populated for worker protection.', related_name='safety_action_proposals', to='assets.asset')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_proposals', to='safety.projectsafetyalert')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_safety_actions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_safety_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='safetytelegramdelivery',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Set for an approved worker-protection instruction. Null for a recorded-decision message to responsible managers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_deliveries', to='safety.safetyactionproposal'),
        ),
        migrations.AddIndex(
            model_name='safetyactionproposal',
            index=models.Index(fields=['status', '-proposed_at'], name='safety_proposal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyactionproposal',
            index=models.Index(fields=['alert', 'decision_type', 'status'], name='safety_proposal_alert_idx'),
        ),
        migrations.AddConstraint(
            model_name='safetyactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('decision_type__in', ('worker_protection', 'asset_protection'))), name='safety_proposal_decision_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='safetyactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('pending_manager_review', 'approved', 'rejected'))), name='safety_proposal_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='safetyactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('proposed_action__in', ('suspend_outdoor_work', 'delay_shift', 'modify_working_hours', 'increase_precautions', 'inspect_site', 'monitor', 'other'))), name='safety_proposal_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='safetyactionproposal',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'pending_manager_review')), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False)), _connector='OR'), name='safety_proposal_review_fields_consistent'),
        ),
        migrations.AddConstraint(
            model_name='safetyactionproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'pending_manager_review')), fields=('alert', 'decision_type'), name='unique_open_safety_proposal_per_alert_type'),
        ),
    ]
