# Generated by Django 5.0.7 on 2026-09-18 11:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('notifications', '0004_notification_safety_category'),
        ('projects', '0002_phase_critical_priority'),
        ('safety', '0006_action_proposal_and_worker_instructions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTelegramDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_id', models.CharField(help_text='Numeric Telegram chat/group/channel id. Never a phone number or an @username.', max_length=32, validators=[django.core.validators.RegexValidator(message='Enter a numeric Telegram chat id (5-20 digits, optionally negative).', regex='^-?[0-9]{5,20}$')])),
                ('display_name', models.CharField(blank=True, default='', help_text="Human label for this destination, e.g. 'Site A crew channel'.", max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='safetytelegramrecipient',
            name='receives_worker_instructions',
        ),
        migrations.AddField(
            model_name='safetyactionproposal',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyactionproposal',
            name='effective_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyactionproposal',
            name='worker_scope',
            field=models.CharField(blank=True, default='', help_text="Which people the action covers, e.g. 'outdoor crews on level 3'. Worker protection only.", max_length=255),
        ),
        migrations.AlterField(
            model_name='safetytelegramdelivery',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='safety.safetytelegramrecipient'),
        ),
        migrations.AddConstraint(
            model_name='safetyactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('effective_from__isnull', True), ('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='safety_proposal_window_ordered'),
        ),
        migrations.AddField(
            model_name='projecttelegramdestination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttelegramdestination',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_destinations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='safetytelegramdelivery',
            name='project_destination',
            field=models.ForeignKey(blank=True, help_text="Set for an approved worker instruction, which is addressed to the affected project's channel. Mutually exclusive with `recipient`.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_deliveries', to='safety.projecttelegramdestination'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'project_destination', 'event_key'), name='unique_safety_telegram_delivery_destination_event'),
        ),
        migrations.AddConstraint(
            model_name='safetytelegramdelivery',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('project_destination__isnull', True), ('recipient__isnull', False)), models.Q(('project_destination__isnull', False), ('recipient__isnull', True)), _connector='OR'), name='safety_tg_delivery_single_audience'),
        ),
        migrations.AddIndex(
            model_name='projecttelegramdestination',
            index=models.Index(fields=['project', 'is_enabled'], name='safety_tg_dest_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='projecttelegramdestination',
            constraint=models.UniqueConstraint(fields=('project', 'chat_id'), name='unique_project_telegram_destination'),
        ),
        migrations.AddConstraint(
            model_name='projecttelegramdestination',
            constraint=models.CheckConstraint(check=models.Q(('chat_id__regex', '^-?[0-9]{5,20}$')), name='project_telegram_chat_id_format'),
        ),
    ]
