# Generated by Django 5.0.7 on 2026-08-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_seed_roles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_email_6f2530_idx',
            old_name='users_user_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_usernam_65d164_idx',
            old_name='users_user_username_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_role_id_a0934c_idx',
            old_name='users_user_role_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
