# Generated by Django 5.0.7 on 2026-08-07 19:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('expected_execution_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_orders', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fault_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('critical', 'Critical')], max_length=10)),
                ('discovery_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faults', to='assets.asset')),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_faults', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_faults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['asset', 'status'], name='fault_asset_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fault',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ('minor', 'moderate', 'major', 'critical'))), name='fault_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='fault',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('reported', 'investigating', 'resolved', 'closed'))), name='fault_status_valid'),
        ),
        migrations.AddIndex(
            model_name='maintenanceorder',
            index=models.Index(fields=['asset', 'status'], name='maint_order_asset_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceorder',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ('preventive', 'corrective', 'emergency'))), name='maintenance_order_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceorder',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ('low', 'medium', 'high', 'urgent'))), name='maintenance_order_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceorder',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('open', 'assigned', 'in_progress', 'completed', 'closed'))), name='maintenance_order_status_valid'),
        ),
    ]
