# Generated by Django 5.0.7 on 2026-08-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='facilities.facility'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['facility'], name='asset_facility_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['current_status'], name='asset_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('current_status__in', ('operational', 'under_maintenance', 'out_of_service'))), name='asset_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('health_score__gte', 0), ('health_score__lte', 100)), name='asset_health_score_range'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('remaining_useful_life__isnull', True), ('remaining_useful_life__gte', 0), _connector='OR'), name='asset_rul_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('operation_date__isnull', True), ('operation_date__gte', models.F('installation_date')), _connector='OR'), name='asset_operation_after_install'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(check=models.Q(('last_maintenance_date__isnull', True), ('last_maintenance_date__gte', models.F('installation_date')), _connector='OR'), name='asset_maintenance_after_install'),
        ),
    ]
