# Generated by Django 5.0.7 on 2026-08-07 19:05

import apps.attachments.storage
import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100)),
                ('module', models.CharField(choices=[('construction', 'Construction'), ('materials', 'Materials'), ('assets', 'Assets'), ('maintenance', 'Maintenance'), ('security', 'Security')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('file_path', models.FileField(blank=True, max_length=500, null=True, storage=apps.attachments.storage.get_protected_storage, upload_to=apps.reports.models.report_upload_path, validators=[apps.reports.models.validate_report_file])),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('construction', 'Construction'), ('materials', 'Materials'), ('assets', 'Assets'), ('maintenance', 'Maintenance'), ('security', 'Security')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('configuration', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('module__in', ('construction', 'materials', 'assets', 'maintenance', 'security'))), name='report_module_valid'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('format__in', ('pdf', 'excel'))), name='report_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('queued', 'processing', 'completed', 'failed'))), name='report_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(('created_by__isnull', False)), name='report_creator_required'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'completed'), _negated=True), ('file_path__isnull', False), _connector='OR'), name='report_completed_has_file'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.CheckConstraint(check=models.Q(('module__in', ('construction', 'materials', 'assets', 'maintenance', 'security'))), name='report_template_module_valid'),
        ),
        migrations.AddConstraint(
            model_name='reporttemplate',
            constraint=models.CheckConstraint(check=models.Q(('format__in', ('pdf', 'excel'))), name='report_template_format_valid'),
        ),
    ]
