# Generated by Django 5.0.7 on 2026-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_device_registration_and_push_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('project', 'Project'), ('material', 'Material'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('safety', 'Safety'), ('system', 'System')], max_length=20),
        ),
    ]
